---
- name: Playbook to configure Edge Environments
  hosts: all
  become: true
  gather_facts: true
  collections:
    - gartner.demo
  tasks:
    - name: Remove all containers
      shell: |
        podman rm -f $(podman ps -a -q);
      ignore_errors: true

    - name: Set container image
      set_fact:
        container_image: "{{ demo_image }}"  

    - name: Import configure role
      import_role:
        name: gartner.demo.configure

    - name: Stat for aws instance
      set_stats:
        data: 
          aws_edge_address: "http://{{ hostvars[inventory_hostname].public_ip_address }}"
        per_host: yes
        aggregate: no
      when: group_names[0] == 'aws_ec2'

    - name: Stat for gcp
      set_stats:
        data:
          gcp_edge_address: "http://{{ hostvars[inventory_hostname].ansible_host }}"
        per_host: yes
        aggregate: no
      when: group_names[0] == 'gcp' or group_names[0] == 'ungrouped'


