---
- name: Playbook to configure Edge Environments
  hosts: all
  become: true
  collections:
    - gartner.demo
    - containers.podman
  tasks:
    - name: Remove all containers
      shell: |
        podman rm $(docker ps -a -q);

    - name: Set container image
      set_fact:
        container_image: "{{ demo_image }}"  

    - name: Import configure role
      import_role:
        name: gartner.demo.configure
