---
- name: Playbook to configure Edge Environments
  hosts: all
  become: true
  gather_facts: true
  collections:
    - gartner.demo
  tasks:
    - name: Remove all containers
      shell: |
        podman rm -f $(podman ps -a -q);
      ignore_errors: true

    - name: Set container image
      set_fact:
        container_image: "{{ demo_image }}"  

    - name: Import configure role
      import_role:
        name: gartner.demo.configure

    - name: debug
      debug: 
        var: hostvars[inventory_hostname].public_ip_address
      when: group_names[0] == 'aws_ec2'

    - name: debug
      debug:
        var: var: hostvars[inventory_hostname].ansible_host
      when: group_names[0] == 'gcp' or group_names[0] == 'ungrouped'
